### ISSUE TITLE
Setup Matomo for Admin

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/product-pipe#5]
From a technical point of view, Matomo tracking on /admin pages has been enabled.
Now it´s about setting up the tracking in a meaningful way, separating Admin user visits from shopper visits, create user segments + respective funnels.

### Next Steps

- [ ] Separate traffic in shops by excluding users who are in fact admins, as their behaviour is different to shoppers

- **Customers** are defined as never visiting a page in with /admin/ in the URL
- **Admins** are defined as people. who have visited a page with /admin/ in the URL.

 
- [ ] Come up with scenarios / simple funnels or events that would be useful to track to have one example that can be documented and “reused”/adjust

- [ ] Set up potentially the **tag manager data layer**:  This is a code change where we surface data about the user and add it to events. We could add things like isLoggedIn, isAdmin or even some variables that help categorise them as shopper types (eg hasNeverPurchased). This data then allows for much more accurate segments. https://matomo.org/docs/tag-manager/#data-layer

**Comment by jaycmb** [comment]
Notes / Actions from conversation with @mbudm 

- Tag Manager Data Layer needs to be set up, because clear separation of shoppers (as users who never visited and /admin page) is otherwise not possible  (and will also facilitate many other analytics for non-devs) 

- [ ] -> @jaycmb will create an issue and assign @mbudm 

- Currently split of Admin users is possible by a "workaround" (create all /admin pages visits segment) , already set up for Australia, 

- [ ] @jaycmb to define "ADMIN" segment for FR, UK, Katuma etc as next steps
